### ISSUE TITLE
Publish a docker container?

### ISSUE THREAD

**Issue by 9876691** [Chainlit/chainlit#178]
Would you consider creating a docker container in the release workflow.

For my use case I'll be deploying to kubernetes.
I have an API end point that takes a prompt and generates a result.

So I'd like to run something like

```
docker run --rm ghcr.io/Chainlit/chainlit:latest https://my-api-endpoint:8080
```

And it automatically just works.

The code to create a container in the release and have it appear in the github packes section of the repo would look something like...

```
....

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
         
    - name: Log in to the Github Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker file
      run: |
        docker build -t ghcr.io/Chainlit/chainlit
        docker push ghcr.io/Chainlit/chainlit
```

I guess for the `Dockerfile` a standard python image could be used.

Thanks
