### ISSUE TITLE
MCP support for more commands

### ISSUE THREAD

**Issue by Aki-community** [Chainlit/chainlit#2004]
**Is your feature request related to a problem? Please describe.**
It's related to MCP usage. When I add a local MCP tool, it says only 'npx' or 'uvx' commands are allowed.

**Describe the solution you'd like**
Please don't set limitation on this or add a configuration to allow cusomized mcp command. Many local mcp servers doesn't onboard to npx or uvx.

**Comment by willydouhard** [comment]
What command are you using out of curiosity?

**Comment by Ryuya1995** [comment]
npm/node/python and customized command.
For example, I've developed a mcp server and I have shared it with hundreds of people in my company. They installed the tool through a command similar to pip install xxx. Then they only need to add xxx as command in their mcp clients.

**Comment by Ryuya1995** [comment]
If it's security concern, it would be nice to be able to config the allow list.

**Comment by ainamdar-ag** [comment]
@Ryuya1995 , you can update `.chainlit/config.toml` and add the commands to this list:

```toml
[features.mcp.stdio]
    enabled = true
    # Only the executables in the allow list can be used for MCP stdio server.
    # Only need the base name of the executable, e.g. "npx", not "/usr/bin/npx".
    # Please don't comment this line for now, we need it to parse the executable name.
    allowed_executables = [ "npx", "uvx", "python" ]
```
