### ISSUE TITLE
Alert "this app does not support MCP" shown on new chat with MCP disabled

### ISSUE THREAD

**Issue by fcestari** [Chainlit/chainlit#2106]
**Describe the bug**
An alert (screenshot below) is shown every time a new chat is started for a chainlit app with MCP disabled in the configs: 

```toml
[features.mcp]
    enabled = false

[features.mcp.sse]
    # Enable or disable the SSE connection type globally
    enabled = false

[features.mcp.stdio]
    # Enable or disable the stdio connection type globally
    enabled = false
    # Define an allowlist of executables for the stdio type.
    # Only the base names of executables listed here can be used.
    # This is a crucial security measure for stdio connections.
    # Example: allows running `npx ...` and `uvx ...` but blocks others.
    allowed_executables = [ "npx", "uvx" ]
```

**Expected behavior**
Do not show the alert and avoid the confusion to the users, as it suggests that the MCP feature is still active despite being disabled.

**Screenshots**

![Image](https://github.com/user-attachments/assets/63ecb67a-c983-489d-9442-927c8668504f)
