### ISSUE TITLE
Loading animation keeps showing after response stream complete

### ISSUE THREAD

**Issue by umair313** [Chainlit/chainlit#2163]
**Describe the bug**
when using stream animation shows on UI a cirlcle start to blink but when stream response completed the loader animation remains at the end of response 

**To Reproduce**
Use the default stream feature and chat on that

**Expected behavior**
When stream start it show the animation but when stream ends the animation showed not be showed until new message

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: Laptop, android
- OS: Ubuntu 24
- Browser: Chrome
- Version

**Additional context**
poetry toml file 

```toml
[tool.poetry]
name = "ABC"
version = "0.1.0"
description = ""
authors = ["umair"]
readme = "README.md"
packages = []  # Empty since this is not a package

[tool.poetry.dependencies]
python = ">=3.12.4,<3.14"
langchain = ">=0.3.25,<0.4.0"
langchain-core = ">=0.3.59,<0.4.0"
langchain-pinecone = ">=0.2.6,<0.3.0"
notebook = ">=7.4.2,<8.0.0"
langchain-openai = ">=0.3.16,<0.4.0"
python-dotenv = ">=1.1.0,<2.0.0"
pandas = ">=2.2.3,<3.0.0"
langgraph = ">=0.4.3,<0.5.0"
streamlit = ">=1.45.0,<2.0.0"
chainlit = ">=2.5.5,<3.0.0"
langchain-community = ">=0.3.23,<0.4.0"
pypdf = "^5.5.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
```

![Image](https://github.com/user-attachments/assets/1b15599d-63b0-4e00-a876-c0466d40f863)
