### ISSUE TITLE
Hex Color Override Improvements in config.toml

### ISSUE THREAD

**Issue by hayescode** [Chainlit/chainlit#673]
I have requirements to match the Chainlit UI to internal branding as the default view. Customizing the light theme (default) changes some, but not all, of the UI elements.

- The text is always black (White in dark mode)
- The chatbot response is not configurable (White)
- It would be nice to customize the font-family

```toml
[UI.theme.light]
    background = "#17234E"
    paper = "#1F397F" #102040

    [UI.theme.light.primary]
        # main = "#FFFFFF"
        # dark = "#6495ED"
        # light = "#6495ED"

[UI.theme.dark]
    #background = "#444654"
    #paper = "#343541"

    [UI.theme.dark.primary]
        main = "#00CED1"
        dark = "#6495ED"
        light = "#00CED1"
```

[Discord Thread](https://discord.com/channels/1088038867602526210/1126876648839598130/1179752317868834867)

![image](https://github.com/Chainlit/chainlit/assets/35790761/8ac47393-0e72-46ef-a14f-c99fb6b0ccf8)
