### ISSUE TITLE
can not define custom `lc_cache_path` when cache enabled

### ISSUE THREAD

**Issue by necjamahim** [Chainlit/chainlit#987]
**Describe the bug**
When defining lc_cache_path and enabling cache in config type error is thrown with message "got multiple values for keyword argument lc_cache_path.

**To Reproduce**
1. enable cache and define custom langchain cache path.
``` toml
# Enable third parties caching (e.g LangChain cache)
cache = true
lc_cache_path = './.custom-cache-path.db'
```
2. start chainlit server

TypeError is thrown:
``` bash
TypeError: chainlit.config.ProjectSettings() got multiple values for keyword argument 'lc_cache_path'
```

**Expected behavior**
sqllite db file is created at specified path on OS `./.custom-cache-path.db`

**Desktop**
- macOS14.4.1
- chainlit1.0.506

**additional context**
PR to resolve this issue: https://github.com/Chainlit/chainlit/pull/982
